name: CI/CD Pipeline for OpenSupports

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Step 1: Deploy to the Development environment
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to configure AWS credentials using secrets (replace with your own)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform in the development environment
      - name: Terraform Init
        run: terraform init

      # Deploy infrastructure to the development environment
      - name: Deploy to Development
        run: terraform apply -auto-approve -var="environment=development"

  # Step 2: Deploy to Staging after successful dev deployment
  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev  # This ensures staging runs after development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      # Deploy infrastructure to the staging environment
      - name: Deploy to Staging
        run: terraform apply -auto-approve -var="environment=staging"

  # Step 3: Deploy to Production after successful staging deployment
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging  # This ensures production runs after staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      # Deploy infrastructure to the production environment
      - name: Deploy to Production
        run: terraform apply -auto-approve -var="environment=production"

